projetoAvaliacaoTempoTelecom/pedidos/urls.py
from django.urls import path
from . import views

app_name = 'pedidos'
urlpatterns = [
    path('', views.index, name='index'),

    path('clientes/', views.clientes, name='clientes'),
    path('clientes/<int:cliente_id>/', views.cliente, name='cliente'),
    path('novo_usuario/', views.cliente_create, name='cliente_create'),
    path('produtos/', views.produtos, name='produtos'),
    path('novo_produto/', views.produto_create, name='produto_create'),
    path('pedidos/', views.pedidos, name='pedidos'),
    # path('novo_pedido/', views.pedido_create, name='pedido_create'),
]

projetoAvaliacaoTempoTelecom/projetoAvaliacaoTempoTelecom/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pedidos.urls'))
]

projetoAvaliacaoTempoTelecom/pedidos/models.py
from django.db import models


class Produto(models.Model):
    nome = models.CharField(max_length=100, blank=False, null=False)
    valor = models.DecimalField(max_digits=12, decimal_places=2, null=False, help_text="Formato: 1234567.89")
    # Valor máximo 9 999 999 999,99 -> 12 dígitos
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nome


class Cliente(models.Model):
    nome = models.CharField(max_length=100, blank=False, null=False)
    # Exemplo de telefone: 55 62 99183 7421 -> 13 dígitos
    telefone = models.DecimalField(max_digits=13, decimal_places=0, null=False, help_text="Formato: 5562912345678")
    data_nascimento = models.DateField(null=False, help_text="Formato: dd/mm/aaaa")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nome


class Pedido(models.Model):
    # numero do pedido -> id, auto incrementado e único para cada objeto/tupla do banco
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    produto = models.ManyToManyField(Produto)
    valor_total = models.DecimalField(max_digits=12, decimal_places=2, null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

projetoAvaliacaoTempoTelecom/pedidos/forms.py
from django.forms import ModelForm

from .models import Cliente, Produto, Pedido


class ClienteForm(ModelForm):
    class Meta:
        model = Cliente
        fields = ['nome', 'telefone', 'data_nascimento']


class ProdutoForm(ModelForm):
    class Meta:
        model = Produto
        fields = ['nome', 'valor']


class PedidoForm(ModelForm):
    class Meta:
        model = Pedido
        fields = ['cliente', 'produto', 'valor_total']

projetoAvaliacaoTempoTelecom/pedidos/views.py
from django.shortcuts import render, get_object_or_404, HttpResponse, redirect
from django.http import Http404, HttpResponseRedirect

from .models import Cliente, Produto, Pedido
from .forms import ClienteForm, ProdutoForm, PedidoForm

import datetime


def index(request):
    Cliente.objects.get_or_create(
        nome='Carlos Henrique Duarte Luz',
        telefone=5562991837421,
        data_nascimento=datetime.date(1993, 4, 19)
    )
    Produto.objects.get_or_create(
        nome='Batata',
        valor='2.00'
    )
    return render(request, 'pedidos/index.html')


def clientes(request):
    latest_clientes_list = Cliente.objects.order_by('-created_at')
    context = {
        'latest_clientes_list': latest_clientes_list,
    }
    return render(request, 'pedidos/clientes.html', context)


def cliente(request, cliente_id):
    try:
        cliente = Cliente.objects.get(pk=cliente_id)
    except Cliente.DoesNotExist:
        raise Http404("Cliente não existe!")
    return render(request, 'pedidos/cliente.html', {'cliente': cliente})


def cliente_create(request):
    form = ClienteForm()

    if request.method == 'POST':

        form = ClienteForm(request.POST)

        if form.is_valid():
            cliente_nome=form.cleaned_data['nome']
            cliente_telefone=form.cleaned_data['telefone']
            cliente_data_nascimento=form.cleaned_data['data_nascimento']

            novo_cliente=Cliente(
                nome=cliente_nome,
                telefone=cliente_telefone,
                data_nascimento=cliente_data_nascimento
            )
            novo_cliente.save()

            return redirect('pedidos:clientes')

    return render(request, 'pedidos/add_cliente.html', {'form': form})


def produtos(request):
    latest_produtos_list = Produto.objects.order_by('-created_at')
    return render(request, 'pedidos/produtos.html', {'latest_produtos_list': latest_produtos_list})


def produto_create(request):
    form = ProdutoForm()

    if request.method == 'POST':

        form = ProdutoForm(request.POST)

        if form.is_valid():
            produto_nome=form.cleaned_data['nome']
            produto_valor=form.cleaned_data['valor']

            novo_produto=Produto(
                nome=produto_nome,
                valor=produto_valor,
            )
            novo_produto.save()

            return redirect('pedidos:produtos')

    return render(request, 'pedidos/add_produto.html', {'form': form})


def pedidos(request):
    latest_pedidos_list = Pedido.objects.order_by('-created_at')
    return render(request, 'pedidos/pedidos.html', {'latest_pedidos_list': latest_pedidos_list})


def pedido_create(request):
    form = PedidoForm()

    if request.method == 'POST':

        form = PedidoForm(request.POST)

        if form.is_valid():
            pedido_cliente = form.cleaned_data['cliente']
            pedido_produto = form.cleaned_data['produto']
            pedido_valor_total = form.cleaned_data['valor_total']

            novo_pedido=Produto(
                cliente=pedido_cliente,
                produto=pedido_produto,
                valor_total=pedido_valor_total,
            )
            novo_pedido.save()

            return redirect('pedidos:pedidos')

    return render(request, 'pedidos/add_pedido.html', {'form': form})

projetoAvaliacaoTempoTelecom/pedidos/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/pedidos.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="\">Avaliação Tempo Telecom</a>
        </div>
            <ul class="nav navbar-nav">
                <li><a href="{% url 'pedidos:pedidos' %}">Pedidos</a></li>
                <li><a href="{% url 'pedidos:clientes' %}">Clientes</a></li>
                <li><a href="{% url 'pedidos:produtos' %}">Produtos</a></li>
            </ul>
        </div>
</nav>
    <div class="block-content">
        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>

projetoAvaliacaoTempoTelecom/pedidos/templates/pedidos/add_cliente.html
{% extends "base.html" %}

{% block content %}

    <h1>Novo Cliente</h1>
    <div>
        <form action="." method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-default" value="Criar">
        </form>
    </div>

{% endblock content %}

projetoAvaliacaoTempoTelecom/pedidos/templates/pedidos/add_pedido.html
{% extends "base.html" %}

{% block content %}

    <h1>Novo Pedido</h1>
    <div>
        <form action="." method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-default" value="Criar">
        </form>
    </div>

{% endblock content %}

projetoAvaliacaoTempoTelecom/pedidos/templates/pedidos/add_produto.html
{% extends "base.html" %}

{% block content %}

    <h1>Novo Produto</h1>
    <div>
        <form action="." method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-default" value="Criar">
        </form>
    </div>

{% endblock content %}

projetoAvaliacaoTempoTelecom/pedidos/templates/pedidos/cliente.html
{% extends 'base.html' %}

{% block content %}

    <h1>Cliente {{ cliente.id }}</h1>
    <p>
        Nome: {{ cliente.nome }}
        <br>
        Telefone: {{ cliente.telefone }}
        <br>
        Data de nascimento: {{ cliente.nascimento|date:"j n Y" }}
    </p>

{% endblock content %}

projetoAvaliacaoTempoTelecom/pedidos/templates/pedidos/clientes.html
{% extends 'base.html' %}

{% block content %}

{{ STATIC_URL }}

    <h1>Clientes</h1>

    {% if latest_clientes_list %}
    <ul>
    {% for cliente in latest_clientes_list %}
        <li><a href="{% url 'pedidos:cliente'  cliente.id %}">{{ cliente.nome }}</a></li>
    {% endfor %}
    </ul>
    {% else %}
        <p>Nenhum cliente disponível.</p>
    {% endif %}

    <a href="{% url 'pedidos:cliente_create' %}" class="btn btn-primary">Novo</a>

{% endblock content %}

projetoAvaliacaoTempoTelecom/pedidos/templates/pedidos/index.html
{% extends "base.html" %}

{% block content %}

    <h1>Bem vindo</h1>
    <p>Tente o menu!</p>

{% endblock content %}

projetoAvaliacaoTempoTelecom/pedidos/templates/pedidos/pedidos.html
{% extends 'base.html' %}

{% block content %}

{{ STATIC_URL }}

    <h1>Pedidos</h1>

    {% if latest_pedidos_list %}
    <ul>
    {% for pedido in latest_pedidos_list %}
        <li>Pedido {{ pedido.id }}</li>
    {% endfor %}
    </ul>
    {% else %}
        <p>Nenhum pedido disponível.</p>
    {% endif %}

<!--    <a href="{# url 'pedidos:pedido_create' #}" class="btn btn-primary">Novo</a>-->

{% endblock content %}

projetoAvaliacaoTempoTelecom/pedidos/templates/pedidos/produtos.html
{% extends 'base.html' %}

{% block content %}

{{ STATIC_URL }}

    <h1>Produtos</h1>

    {% if latest_produtos_list %}
    <ul>
    {% for produto in latest_produtos_list %}
        <li>Nome: {{ produto.nome }}, Valor: R$ {{ produto.valor }}</li>
    {% endfor %}
    </ul>
    {% else %}
        <p>Nenhum produto disponível.</p>
    {% endif %}

    <a href="{% url 'pedidos:produto_create' %}" class="btn btn-primary">Novo</a>

{% endblock content %}